networks:
  docker.network:
    driver: bridge

services:
  php:
    container_name: php
    build: ../task_tracker/docker/php/
    depends_on:
      - db
    networks:
      - docker.network
    volumes:
      - ./:/application

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    depends_on:
      - php
    ports:
      - "80:80"
    networks:
      - docker.network
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/application/public

  db:
    container_name: postgres
    image: postgres:15.1-alpine3.17
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - docker.network
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: { }
